// <auto-generated />
using System;
using EdSkill.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdSkill.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518151042_AddProfileDashboardMySpaceAndReviewDashboard")]
    partial class AddProfileDashboardMySpaceAndReviewDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EdSkill.Domain.Entities.AchievementDefinition", b =>
                {
                    b.Property<Guid>("AchievementDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Threshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("AchievementDefinitionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AchievementDefinitions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.CompanionSpaceCard", b =>
                {
                    b.Property<Guid>("CompanionSpaceCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CredentialUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("DeliveryModes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Languages")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<int>("PricePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanionSpaceCardId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "Title");

                    b.ToTable("CompanionSpaceCards");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.LearnerSpaceCard", b =>
                {
                    b.Property<Guid>("LearnerSpaceCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeliveryModes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Languages")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LearnerSpaceCardId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "Title");

                    b.ToTable("LearnerSpaceCards");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountVnd")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("PointPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("PointPackageId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("Provider", "ProviderTransactionId")
                        .IsUnique()
                        .HasFilter("[ProviderTransactionId] IS NOT NULL AND [Status] = 'Success'");

                    b.HasIndex("UserId", "Status", "CreatedAt");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PointPackage", b =>
                {
                    b.Property<Guid>("PointPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BadgeText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BonusPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHighlighted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("PriceVnd")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("PointPackageId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted", "IsActive", "DisplayOrder");

                    b.ToTable("PointPackages");

                    b.HasData(
                        new
                        {
                            PointPackageId = new Guid("91000000-0000-0000-0000-000000000001"),
                            BonusPoints = 0,
                            Code = "goi_1",
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Gói nạp 500 Points.",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsHighlighted = false,
                            Name = "Gói 1",
                            Points = 500,
                            PriceVnd = 59000,
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PointPackageId = new Guid("91000000-0000-0000-0000-000000000002"),
                            BonusPoints = 0,
                            Code = "goi_2",
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Gói nạp 1.000 Points.",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            IsHighlighted = false,
                            Name = "Gói 2",
                            Points = 1000,
                            PriceVnd = 99000,
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PointPackageId = new Guid("91000000-0000-0000-0000-000000000003"),
                            BonusPoints = 0,
                            Code = "goi_3",
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Gói nạp 2.000 Points.",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            IsHighlighted = false,
                            Name = "Gói 3",
                            Points = 2000,
                            PriceVnd = 169000,
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PointPackageId = new Guid("91000000-0000-0000-0000-000000000004"),
                            BonusPoints = 0,
                            Code = "goi_4",
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            Description = "Gói nạp 5.000 Points.",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsDeleted = false,
                            IsHighlighted = false,
                            Name = "Gói 4",
                            Points = 5000,
                            PriceVnd = 379000,
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("PointTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HeldBalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("HeldBalanceBefore")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SystemLedgerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PointTransactionId");

                    b.HasIndex("SystemLedgerAccountId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PointWallet", b =>
                {
                    b.Property<Guid>("PointWalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HeldBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PointWalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PointWallets");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PolicyConsent", b =>
                {
                    b.Property<Guid>("PolicyConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyConsentId");

                    b.HasIndex("UserId", "PolicyType", "PolicyVersion")
                        .IsUnique();

                    b.ToTable("PolicyConsents");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PolicyDocument", b =>
                {
                    b.Property<Guid>("PolicyDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PolicyType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresAcceptance")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("PolicyDocumentId");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("PolicyDocuments");

                    b.HasData(
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Audience = "all",
                            Category = "legal",
                            ContentMarkdown = "# Điều khoản sử dụng EdSkill\n\nEdSkill là nền tảng kết nối Learner và Companion để trao đổi kỹ năng theo hình thức 1-1 trong phạm vi Phase 1 MVP.\n\n## Quy định chung\n\n- Người dùng phải cung cấp thông tin đúng sự thật khi đăng ký và cập nhật hồ sơ.\n- Learner không được tự đặt phiên với chính mình.\n- Mọi hoạt động trên nền tảng phải tuân thủ quy định pháp luật, quy tắc cộng đồng và các chính sách hiện hành của EdSkill.\n- EdSkill có quyền tạm khóa hoặc chấm dứt quyền truy cập khi phát hiện gian lận, lạm dụng hệ thống, quấy rối hoặc vi phạm chính sách.\n\n## Trách nhiệm của người dùng\n\n- Learner chịu trách nhiệm kiểm tra lịch học, số Points và thông tin phiên trước khi đặt lịch.\n- Companion chịu trách nhiệm mô tả kỹ năng, nội dung hỗ trợ và xác nhận hoặc từ chối phiên đúng luồng hệ thống.\n- Cả hai bên phải tham gia phiên với thái độ chuyên nghiệp, tôn trọng và không đăng tải nội dung trái phép.\n\n## Giới hạn trách nhiệm\n\n- EdSkill cung cấp nền tảng công nghệ và không cam kết kết quả học tập cụ thể.\n- Tranh chấp phát sinh từ hành vi người dùng có thể bị xử lý theo cơ chế hỗ trợ, hoàn điểm hoặc khóa tài khoản tùy mức độ.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "Terms",
                            RequiresAcceptance = true,
                            Slug = "terms",
                            Summary = "Quy định quyền, nghĩa vụ và giới hạn trách nhiệm giữa EdSkill, Learner và Companion.",
                            Title = "Điều khoản sử dụng nền tảng EdSkill",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Audience = "all",
                            Category = "privacy",
                            ContentMarkdown = "# Chính sách riêng tư\n\nEdSkill thu thập dữ liệu cần thiết để vận hành đăng ký, hồ sơ người dùng, phiên học, lịch sử Points/Tokens và thông báo hệ thống.\n\n## Dữ liệu được xử lý\n\n- Thông tin tài khoản: email, username, họ tên, vai trò.\n- Thông tin hồ sơ: bio, kỹ năng, trường, khoa, ảnh đại diện và dữ liệu người dùng tự cập nhật.\n- Dữ liệu vận hành: lịch sử phiên, trạng thái tham gia, giao dịch Points/Tokens, nhật ký đồng ý chính sách.\n\n## Mục đích sử dụng\n\n- Xác thực tài khoản và bảo vệ an toàn hệ thống.\n- Vận hành tính năng đặt lịch, thông báo, hỗ trợ tranh chấp và báo cáo quản trị.\n- Cải thiện chất lượng dịch vụ trong phạm vi cho phép của chính sách này.\n\n## Cam kết\n\n- EdSkill không bán dữ liệu cá nhân của người dùng.\n- Chỉ nhân sự hoặc hệ thống được ủy quyền mới được truy cập dữ liệu phục vụ vận hành, hỗ trợ hoặc tuân thủ pháp lý.\n- Dữ liệu được lưu trong thời hạn phù hợp với nhu cầu vận hành, bảo mật và xử lý khiếu nại.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "Privacy",
                            RequiresAcceptance = true,
                            Slug = "privacy",
                            Summary = "Mô tả cách EdSkill thu thập, lưu trữ và xử lý dữ liệu tài khoản, phiên học và giao dịch.",
                            Title = "Chính sách riêng tư dữ liệu cá nhân",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Audience = "all",
                            Category = "wallet",
                            ContentMarkdown = "# Chính sách Points và Tokens\n\n## Định nghĩa\n\n- Points là đơn vị thanh toán nội bộ của EdSkill để Learner đặt phiên với Companion.\n- Tokens là điểm thưởng loyalty để ghi nhận hoạt động tích cực, không dùng thanh toán trực tiếp cho phiên học.\n\n## Cam kết bắt buộc\n\n- Points và Tokens không phải tiền điện tử, tài sản ảo hoặc sản phẩm đầu tư.\n- Points và Tokens không được quy đổi thành tiền mặt, không được rút ra ngân hàng và không được giao dịch ngoài nền tảng.\n- Mọi thay đổi số dư Points hoặc Tokens đều phải đi qua giao dịch hệ thống và được ghi log.\n\n## Quy tắc sử dụng\n\n- Learner chỉ được đặt phiên khi có đủ Points theo chi phí phiên.\n- Companion nhận Points theo cơ chế giải ngân hợp lệ của hệ thống.\n- EdSkill có quyền điều chỉnh, hoàn hoặc khóa giao dịch khi phát hiện lỗi hệ thống, gian lận hoặc tranh chấp hợp lệ.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "PointsTokens",
                            RequiresAcceptance = true,
                            Slug = "points-tokens",
                            Summary = "Làm rõ Points là đơn vị nội bộ để thanh toán phiên, Tokens là loyalty reward; không phải crypto và không quy đổi tiền mặt.",
                            Title = "Chính sách Points và Tokens",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Audience = "all",
                            Category = "sessions",
                            ContentMarkdown = "# Chính sách hủy phiên, hoàn điểm và no-show\n\n## Hủy phiên\n\n- Learner được hủy không mất Points khi phiên đang ở trạng thái hợp lệ và thời điểm hủy sớm hơn ít nhất 2 giờ trước giờ bắt đầu.\n- Nếu Learner hủy muộn sau mốc 2 giờ, hệ thống mặc định không hoàn Points cho Learner.\n\n## Phân bổ khi hủy muộn\n\n- Tỷ lệ mặc định của nền tảng là Companion nhận 80% và EdSkill ghi nhận 20% khi hủy muộn thuộc trường hợp áp dụng.\n- Cách xử lý cuối cùng vẫn phụ thuộc trạng thái phiên, log tham gia và quy trình dispute của hệ thống.\n\n## No-show và tranh chấp\n\n- No-show hoặc lỗi phát sinh trong phiên có thể được admin xem xét theo hồ sơ tham gia và log hệ thống.\n- Kết quả xử lý có thể là hoàn Points cho Learner, thanh toán cho Companion, chia một phần hoặc không hành động tùy case.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresAcceptance = false,
                            Slug = "cancellation-refund",
                            Summary = "Quy định hủy sớm, hủy muộn, hoàn Points, no-show và hướng xử lý dispute trong MVP.",
                            Title = "Chính sách hủy phiên, hoàn điểm và no-show",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000005"),
                            Audience = "learner",
                            Category = "community",
                            ContentMarkdown = "# Community Guidelines cho Learner\n\n- Tôn trọng thời gian, kỹ năng và công sức của Companion.\n- Mô tả nhu cầu học rõ ràng, không spam, không quấy rối và không yêu cầu nội dung trái pháp luật.\n- Tham gia phiên đúng giờ, xác nhận hoàn thành trung thực và gửi review có trách nhiệm.\n- Không chia sẻ tài khoản, không lạm dụng chính sách hoàn điểm và không dùng Points/Tokens sai mục đích.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "CommunityGuidelines",
                            RequiresAcceptance = false,
                            Slug = "community-guidelines-learner",
                            Summary = "Quy tắc ứng xử ngắn gọn dành cho Learner trong profile, chat và phiên học.",
                            Title = "Community Guidelines cho Learner",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000006"),
                            Audience = "companion",
                            Category = "community",
                            ContentMarkdown = "# Community Guidelines cho Companion\n\n- Cung cấp mô tả kỹ năng, phạm vi hỗ trợ và lịch rảnh trung thực.\n- Xác nhận hoặc từ chối phiên đúng thời gian, không dụ giao dịch ngoài nền tảng.\n- Tôn trọng Learner, không phân biệt đối xử, không lạm dụng quyền từ chối hoặc xác nhận hoàn thành sai sự thật.\n- Bảo mật dữ liệu phiên học và không sử dụng thông tin của Learner ngoài mục đích hỗ trợ trên EdSkill.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "CommunityGuidelines",
                            RequiresAcceptance = false,
                            Slug = "community-guidelines-companion",
                            Summary = "Quy tắc ứng xử ngắn gọn dành cho Companion khi tạo hồ sơ, nhận phiên và hỗ trợ Learner.",
                            Title = "Community Guidelines cho Companion",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        });
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ReviewId");

                    b.HasIndex("RevieweeId", "CreatedAt");

                    b.HasIndex("SessionId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CompanionConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompanionPayoutPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CredentialBonusPointsSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Online");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DisbursedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMultiplierPercentSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("DurationOptions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("JitsiRoomId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LearnerChargePoints")
                        .HasColumnType("int");

                    b.Property<bool>("LearnerConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LearnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PlatformFeePoints")
                        .HasColumnType("int");

                    b.Property<int>("PointCost")
                        .HasColumnType("int");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("LegacyManual");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SelectedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SkillBasePointsSnapshot")
                        .HasColumnType("int");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SessionId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SkillId");

                    b.HasIndex("Status");

                    b.HasIndex("CompanionId", "ScheduledAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<int>("BasePointCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IconKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("SubscriptionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BenefitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Monthly");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CompanionBadgeText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanionDailySessionLimitOverride")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompanionTokenRewardRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("VND");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("HasPriorityVisibility")
                        .HasColumnType("bit");

                    b.Property<int>("ImmediateBonusPoints")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("LearnerTokenRewardRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PriceVnd")
                        .HasColumnType("int");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("WeeklyCompanionSessionBonusPoints")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyLearnerSessionBonusPoints")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionPlanId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            SubscriptionPlanId = new Guid("92000000-0000-0000-0000-000000000001"),
                            BenefitsJson = "[\"Tang ngay 200 Point\",\"Voucher 75% hang tuan\",\"Khong quang cao\",\"Uu tien matching\",\"Rebook nhanh\"]",
                            BillingCycle = "Monthly",
                            Code = "learner_pro",
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            DisplayOrder = 1,
                            HasPriorityVisibility = false,
                            ImmediateBonusPoints = 200,
                            IsActive = true,
                            Name = "Learner Pro",
                            PriceVnd = 119000,
                            TargetRole = "Learner",
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeeklyCompanionSessionBonusPoints = 0,
                            WeeklyLearnerSessionBonusPoints = 0
                        },
                        new
                        {
                            SubscriptionPlanId = new Guid("92000000-0000-0000-0000-000000000002"),
                            BenefitsJson = "[\"Ed-Token bonus 30%\",\"Ho so noi bat hon\",\"Uu tien hien thi\",\"Mo nhieu slot hon\",\"Dashboard nang cao\"]",
                            BillingCycle = "Monthly",
                            Code = "companion_pro",
                            CompanionBadgeText = "Companion Pro",
                            CompanionDailySessionLimitOverride = 12,
                            CompanionTokenRewardRatePercent = 30m,
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            DisplayOrder = 2,
                            HasPriorityVisibility = true,
                            ImmediateBonusPoints = 0,
                            IsActive = true,
                            Name = "Companion Pro",
                            PriceVnd = 79000,
                            TargetRole = "Companion",
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeeklyCompanionSessionBonusPoints = 0,
                            WeeklyLearnerSessionBonusPoints = 0
                        },
                        new
                        {
                            SubscriptionPlanId = new Guid("92000000-0000-0000-0000-000000000003"),
                            BenefitsJson = "[\"200 Point cho buoi hoc dau tien trong tuan\",\"200 Point cho buoi huong dan dau tien trong tuan\",\"Learner token 10%\",\"Companion token 6%\",\"Bao gom quyen loi Learner va Companion\"]",
                            BillingCycle = "Monthly",
                            Code = "multi_role_pro",
                            CompanionBadgeText = "Da nang Pro",
                            CompanionDailySessionLimitOverride = 12,
                            CompanionTokenRewardRatePercent = 6m,
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "VND",
                            DisplayOrder = 3,
                            HasPriorityVisibility = true,
                            ImmediateBonusPoints = 0,
                            IsActive = true,
                            LearnerTokenRewardRatePercent = 10m,
                            Name = "Da nang Pro",
                            PriceVnd = 179000,
                            TargetRole = "MultiRole",
                            UpdatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeeklyCompanionSessionBonusPoints = 200,
                            WeeklyLearnerSessionBonusPoints = 200
                        });
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Key = "point.signup_bonus",
                            Description = "Diem khoi dau khi dang ky.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "50"
                        },
                        new
                        {
                            Key = "point.platform_fee_pct",
                            Description = "% phi nen tang tren moi giao dich completed legacy.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Key = "point.platform_markup_pct",
                            Description = "% markup cong len gia Companion cho Formula Pricing.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "25"
                        },
                        new
                        {
                            Key = "token.learner_per_session",
                            Description = "Token Learner nhan sau moi phien hop le legacy.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Key = "token.companion_per_session",
                            Description = "Token Companion nhan sau moi phien hop le legacy.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Key = "token.daily_earn_limit",
                            Description = "Token toi da nhan trong mot ngay.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Key = "token.weekly_earn_limit",
                            Description = "Token toi da nhan trong mot tuan.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "100"
                        },
                        new
                        {
                            Key = "session.min_duration_minutes",
                            Description = "Thoi luong toi thieu de phien hop le.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        },
                        new
                        {
                            Key = "session.cancel_deadline_hours",
                            Description = "So gio truoc phien duoc huy khong mat diem.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "2"
                        },
                        new
                        {
                            Key = "session.late_cancel_companion_pct",
                            Description = "% diem Companion nhan khi Learner huy muon.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "80"
                        },
                        new
                        {
                            Key = "session.late_cancel_platform_pct",
                            Description = "% diem nen tang nhan khi Learner huy muon.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Key = "session.max_per_day_per_companion",
                            Description = "So phien toi da mot Companion mo trong ngay.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "8"
                        },
                        new
                        {
                            Key = "session.buffer_minutes",
                            Description = "Thoi gian nghi toi thieu giua hai phien.",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        });
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.SystemLedgerAccount", b =>
                {
                    b.Property<Guid>("SystemLedgerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SystemLedgerAccountId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SystemLedgerAccounts");

                    b.HasData(
                        new
                        {
                            SystemLedgerAccountId = new Guid("90000000-0000-0000-0000-000000000001"),
                            Balance = 0,
                            Code = "platform_fee",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Platform Fee Ledger",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.TokenBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TokenBlacklist");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.TokenTransaction", b =>
                {
                    b.Property<Guid>("TokenTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenTransactionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("TokenTransactions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[\"learner\"]'");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("active");

                    b.Property<decimal>("TokenBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AwardedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("AchievementDefinitionId");

                    b.HasIndex("UserId", "AchievementDefinitionId")
                        .IsUnique();

                    b.HasIndex("UserId", "AwardedAt");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CredentialUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DegreeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("SkillsToLearn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("SkillsToTeach")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("SocialLinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TotalSessions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "Type")
                        .IsUnique();

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique()
                        .HasFilter("[PaymentTransactionId] IS NOT NULL");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status", "ExpiresAt");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.CompanionSpaceCard", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.LearnerSpaceCard", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.PointPackage", "PointPackage")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PointPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EdSkill.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PointPackage");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PointTransaction", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EdSkill.Domain.Entities.SystemLedgerAccount", "SystemLedgerAccount")
                        .WithMany()
                        .HasForeignKey("SystemLedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");

                    b.Navigation("SystemLedgerAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PointWallet", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithOne("PointWallet")
                        .HasForeignKey("EdSkill.Domain.Entities.PointWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PolicyConsent", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("PolicyConsents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Review", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Session", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "Companion")
                        .WithMany("CompanionSessions")
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "Learner")
                        .WithMany("LearnerSessions")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Companion");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.SystemConfig", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedSystemConfigs")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.TokenTransaction", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("TokenTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.AchievementDefinition", "AchievementDefinition")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("EdSkill.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithOne("UserSubscription")
                        .HasForeignKey("EdSkill.Domain.Entities.UserSubscription", "PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EdSkill.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.AchievementDefinition", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PointPackage", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.User", b =>
                {
                    b.Navigation("CompanionSessions");

                    b.Navigation("LearnerSessions");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("PointTransactions");

                    b.Navigation("PointWallet");

                    b.Navigation("PolicyConsents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TokenTransactions");

                    b.Navigation("UpdatedSystemConfigs");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserProfile");

                    b.Navigation("UserSkills");

                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
