// <auto-generated />
using System;
using EdSkill.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdSkill.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510111342_PolicyConsentMvp")]
    partial class PolicyConsentMvp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EdSkill.Domain.Entities.PolicyConsent", b =>
                {
                    b.Property<Guid>("PolicyConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyConsentId");

                    b.HasIndex("UserId", "PolicyType", "PolicyVersion")
                        .IsUnique();

                    b.ToTable("PolicyConsents");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PolicyDocument", b =>
                {
                    b.Property<Guid>("PolicyDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PolicyType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresAcceptance")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("PolicyDocumentId");

                    b.HasIndex("Slug", "Version")
                        .IsUnique();

                    b.ToTable("PolicyDocuments");

                    b.HasData(
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Audience = "all",
                            Category = "legal",
                            ContentMarkdown = "# Điều khoản sử dụng EdSkill\n\nEdSkill là nền tảng kết nối Learner và Companion để trao đổi kỹ năng theo hình thức 1-1 trong phạm vi Phase 1 MVP.\n\n## Quy định chung\n\n- Người dùng phải cung cấp thông tin đúng sự thật khi đăng ký và cập nhật hồ sơ.\n- Learner không được tự đặt phiên với chính mình.\n- Mọi hoạt động trên nền tảng phải tuân thủ quy định pháp luật, quy tắc cộng đồng và các chính sách hiện hành của EdSkill.\n- EdSkill có quyền tạm khóa hoặc chấm dứt quyền truy cập khi phát hiện gian lận, lạm dụng hệ thống, quấy rối hoặc vi phạm chính sách.\n\n## Trách nhiệm của người dùng\n\n- Learner chịu trách nhiệm kiểm tra lịch học, số Points và thông tin phiên trước khi đặt lịch.\n- Companion chịu trách nhiệm mô tả kỹ năng, nội dung hỗ trợ và xác nhận hoặc từ chối phiên đúng luồng hệ thống.\n- Cả hai bên phải tham gia phiên với thái độ chuyên nghiệp, tôn trọng và không đăng tải nội dung trái phép.\n\n## Giới hạn trách nhiệm\n\n- EdSkill cung cấp nền tảng công nghệ và không cam kết kết quả học tập cụ thể.\n- Tranh chấp phát sinh từ hành vi người dùng có thể bị xử lý theo cơ chế hỗ trợ, hoàn điểm hoặc khóa tài khoản tùy mức độ.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "Terms",
                            RequiresAcceptance = true,
                            Slug = "terms",
                            Summary = "Quy định quyền, nghĩa vụ và giới hạn trách nhiệm giữa EdSkill, Learner và Companion.",
                            Title = "Điều khoản sử dụng nền tảng EdSkill",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Audience = "all",
                            Category = "privacy",
                            ContentMarkdown = "# Chính sách riêng tư\n\nEdSkill thu thập dữ liệu cần thiết để vận hành đăng ký, hồ sơ người dùng, phiên học, lịch sử Points/Tokens và thông báo hệ thống.\n\n## Dữ liệu được xử lý\n\n- Thông tin tài khoản: email, username, họ tên, vai trò.\n- Thông tin hồ sơ: bio, kỹ năng, trường, khoa, ảnh đại diện và dữ liệu người dùng tự cập nhật.\n- Dữ liệu vận hành: lịch sử phiên, trạng thái tham gia, giao dịch Points/Tokens, nhật ký đồng ý chính sách.\n\n## Mục đích sử dụng\n\n- Xác thực tài khoản và bảo vệ an toàn hệ thống.\n- Vận hành tính năng đặt lịch, thông báo, hỗ trợ tranh chấp và báo cáo quản trị.\n- Cải thiện chất lượng dịch vụ trong phạm vi cho phép của chính sách này.\n\n## Cam kết\n\n- EdSkill không bán dữ liệu cá nhân của người dùng.\n- Chỉ nhân sự hoặc hệ thống được ủy quyền mới được truy cập dữ liệu phục vụ vận hành, hỗ trợ hoặc tuân thủ pháp lý.\n- Dữ liệu được lưu trong thời hạn phù hợp với nhu cầu vận hành, bảo mật và xử lý khiếu nại.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "Privacy",
                            RequiresAcceptance = true,
                            Slug = "privacy",
                            Summary = "Mô tả cách EdSkill thu thập, lưu trữ và xử lý dữ liệu tài khoản, phiên học và giao dịch.",
                            Title = "Chính sách riêng tư dữ liệu cá nhân",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Audience = "all",
                            Category = "wallet",
                            ContentMarkdown = "# Chính sách Points và Tokens\n\n## Định nghĩa\n\n- Points là đơn vị thanh toán nội bộ của EdSkill để Learner đặt phiên với Companion.\n- Tokens là điểm thưởng loyalty để ghi nhận hoạt động tích cực, không dùng thanh toán trực tiếp cho phiên học.\n\n## Cam kết bắt buộc\n\n- Points và Tokens không phải tiền điện tử, tài sản ảo hoặc sản phẩm đầu tư.\n- Points và Tokens không được quy đổi thành tiền mặt, không được rút ra ngân hàng và không được giao dịch ngoài nền tảng.\n- Mọi thay đổi số dư Points hoặc Tokens đều phải đi qua giao dịch hệ thống và được ghi log.\n\n## Quy tắc sử dụng\n\n- Learner chỉ được đặt phiên khi có đủ Points theo chi phí phiên.\n- Companion nhận Points theo cơ chế giải ngân hợp lệ của hệ thống.\n- EdSkill có quyền điều chỉnh, hoàn hoặc khóa giao dịch khi phát hiện lỗi hệ thống, gian lận hoặc tranh chấp hợp lệ.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "PointsTokens",
                            RequiresAcceptance = true,
                            Slug = "points-tokens",
                            Summary = "Làm rõ Points là đơn vị nội bộ để thanh toán phiên, Tokens là loyalty reward; không phải crypto và không quy đổi tiền mặt.",
                            Title = "Chính sách Points và Tokens",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Audience = "all",
                            Category = "sessions",
                            ContentMarkdown = "# Chính sách hủy phiên, hoàn điểm và no-show\n\n## Hủy phiên\n\n- Learner được hủy không mất Points khi phiên đang ở trạng thái hợp lệ và thời điểm hủy sớm hơn ít nhất 2 giờ trước giờ bắt đầu.\n- Nếu Learner hủy muộn sau mốc 2 giờ, hệ thống mặc định không hoàn Points cho Learner.\n\n## Phân bổ khi hủy muộn\n\n- Tỷ lệ mặc định của nền tảng là Companion nhận 70% và EdSkill ghi nhận 30% khi hủy muộn thuộc trường hợp áp dụng.\n- Cách xử lý cuối cùng vẫn phụ thuộc trạng thái phiên, log tham gia và quy trình dispute của hệ thống.\n\n## No-show và tranh chấp\n\n- No-show hoặc lỗi phát sinh trong phiên có thể được admin xem xét theo hồ sơ tham gia và log hệ thống.\n- Kết quả xử lý có thể là hoàn Points cho Learner, thanh toán cho Companion, chia một phần hoặc không hành động tùy case.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiresAcceptance = false,
                            Slug = "cancellation-refund",
                            Summary = "Quy định hủy sớm, hủy muộn, hoàn Points, no-show và hướng xử lý dispute trong MVP.",
                            Title = "Chính sách hủy phiên, hoàn điểm và no-show",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000005"),
                            Audience = "learner",
                            Category = "community",
                            ContentMarkdown = "# Community Guidelines cho Learner\n\n- Tôn trọng thời gian, kỹ năng và công sức của Companion.\n- Mô tả nhu cầu học rõ ràng, không spam, không quấy rối và không yêu cầu nội dung trái pháp luật.\n- Tham gia phiên đúng giờ, xác nhận hoàn thành trung thực và gửi review có trách nhiệm.\n- Không chia sẻ tài khoản, không lạm dụng chính sách hoàn điểm và không dùng Points/Tokens sai mục đích.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "CommunityGuidelines",
                            RequiresAcceptance = false,
                            Slug = "community-guidelines-learner",
                            Summary = "Quy tắc ứng xử ngắn gọn dành cho Learner trong profile, chat và phiên học.",
                            Title = "Community Guidelines cho Learner",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        },
                        new
                        {
                            PolicyDocumentId = new Guid("70000000-0000-0000-0000-000000000006"),
                            Audience = "companion",
                            Category = "community",
                            ContentMarkdown = "# Community Guidelines cho Companion\n\n- Cung cấp mô tả kỹ năng, phạm vi hỗ trợ và lịch rảnh trung thực.\n- Xác nhận hoặc từ chối phiên đúng thời gian, không dụ giao dịch ngoài nền tảng.\n- Tôn trọng Learner, không phân biệt đối xử, không lạm dụng quyền từ chối hoặc xác nhận hoàn thành sai sự thật.\n- Bảo mật dữ liệu phiên học và không sử dụng thông tin của Learner ngoài mục đích hỗ trợ trên EdSkill.",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyType = "CommunityGuidelines",
                            RequiresAcceptance = false,
                            Slug = "community-guidelines-companion",
                            Summary = "Quy tắc ứng xử ngắn gọn dành cho Companion khi tạo hồ sơ, nhận phiên và hỗ trợ Learner.",
                            Title = "Community Guidelines cho Companion",
                            UpdatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026-05-10.v1"
                        });
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.TokenBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TokenBlacklist");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[\"learner\"]'");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("active");

                    b.Property<decimal>("TokenBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("SkillsToLearn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("SkillsToTeach")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<int>("TotalSessions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("University")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "Type")
                        .IsUnique();

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.PolicyConsent", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("PolicyConsents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("EdSkill.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("EdSkill.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EdSkill.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EdSkill.Domain.Entities.User", b =>
                {
                    b.Navigation("PolicyConsents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserProfile");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
