<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Auth\Commands\RefreshToken\**" />
    <Compile Remove="Features\Goals\Queries\GetGoalsByUserId\**" />
    <Compile Remove="Features\LearningPathSkeleton\Queries\GetLearningPathById\**" />
    <Compile Remove="Features\Lessons\Commands\ConfirmLessonContent\**" />
    <Compile Remove="Features\Subjects\Queries\GetMySubjects\**" />
    <Compile Remove="Features\Users\Queries\GetMyStatistics\**" />
    <EmbeddedResource Remove="Features\Auth\Commands\RefreshToken\**" />
    <EmbeddedResource Remove="Features\Goals\Queries\GetGoalsByUserId\**" />
    <EmbeddedResource Remove="Features\LearningPathSkeleton\Queries\GetLearningPathById\**" />
    <EmbeddedResource Remove="Features\Lessons\Commands\ConfirmLessonContent\**" />
    <EmbeddedResource Remove="Features\Subjects\Queries\GetMySubjects\**" />
    <EmbeddedResource Remove="Features\Users\Queries\GetMyStatistics\**" />
    <None Remove="Features\Auth\Commands\RefreshToken\**" />
    <None Remove="Features\Goals\Queries\GetGoalsByUserId\**" />
    <None Remove="Features\LearningPathSkeleton\Queries\GetLearningPathById\**" />
    <None Remove="Features\Lessons\Commands\ConfirmLessonContent\**" />
    <None Remove="Features\Subjects\Queries\GetMySubjects\**" />
    <None Remove="Features\Users\Queries\GetMyStatistics\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="NewId" Version="4.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeNexus.Domain\CodeNexus.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Chapters\Queries\GetChapterStatus\" />
    <Folder Include="Features\DailyCheckins\Queries\GetDailyCheckinBySessionId\" />
    <Folder Include="Features\FocusSessions\Commands\" />
    <Folder Include="Features\FocusSessions\DTOs\" />
    <Folder Include="Features\LearningPathSkeleton\Queries\GetAllLearningPaths\" />
    <Folder Include="Features\LearningPathSkeleton\Queries\GetLearningPathByUserId\" />
    <Folder Include="Features\Notifications\Commands\SendTestNotificationEmail\" />
    <Folder Include="Features\Resources\Commands\" />
  </ItemGroup>

</Project>
